/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Negocio.estimulos;
import Modelos.*;
import DAO.*;
import java.awt.event.KeyEvent;
import java.util.Date;

/**
 *
 * @author Joshua
 */
public class GridCompleto extends javax.swing.JFrame {
    
    estimulos e = new estimulos();
    Thread t = new Thread();
    Date d = new Date();
    int id=1;
    boolean arriba=true;
    

    /**
     * Creates new form inicio
     */
    public GridCompleto() {
        initComponents();
        this.setLocationRelativeTo(null);
        cuadrantes();
        Correctorlbl.setText("");
//        if(Incorrecto()){
//            Correctorlbl.setText("Incorrecto");
//        }

    }

     
            
       public void cuadrantes() {
        String c = e.Cadena();
        if (EsPar(c)) {
            if(arriba){
                Cuadrante1tf.setText(c);
            }
            
        } else if(!EsPar(c)){
            if(arriba){
              Cuadrante2tf.setText(c);
              
            }
            arriba=false;
        }else if(EsVocal(c)){
            if(!arriba){
                Cuadrante3tf.setText(c);
            }
        } else if(!EsVocal(c)){
            if(!arriba){
                Cuadrante4tf.setText(c);
            }
            arriba=true;
        }

    }
    

    public boolean EsPar(String cadena) {
        int num = Integer.parseInt(cadena.substring(1));
        if (num % 2 == 0) {
            return true;
        }
        return false;
    }

    public boolean EsVocal(String cadena) {
        String s = cadena.substring(0);
        String v[] = {"A", "E", "I", "O", "U"};
        
        for (int i = 0; i < v.length; i++) {
            if (v[i].equals(s)) {
                return true;
            } else {
                return false;
            }
        }
        
        return false;
    }
//    
//    public Boolean Incorrecto(){
//        
//    }

//    public void IteraTAreas(){
//        d.getTime();
//        Cuadrante1tf.setText(e.Cadena());
//        
//        Cuadrante2tf.setText(CuadranteSiguiente());
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cuadrante1tf = new javax.swing.JTextField();
        Cuadrante4tf = new javax.swing.JTextField();
        Cuadrante3tf = new javax.swing.JTextField();
        Cuadrante2tf = new javax.swing.JTextField();
        Correctorlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        Cuadrante1tf.setEditable(false);
        Cuadrante1tf.setBackground(java.awt.Color.white);
        Cuadrante1tf.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Cuadrante1tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cuadrante1tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Cuadrante1tfKeyPressed(evt);
            }
        });

        Cuadrante4tf.setEditable(false);
        Cuadrante4tf.setBackground(java.awt.Color.white);
        Cuadrante4tf.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Cuadrante4tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Cuadrante3tf.setEditable(false);
        Cuadrante3tf.setBackground(java.awt.Color.white);
        Cuadrante3tf.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Cuadrante3tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Cuadrante2tf.setEditable(false);
        Cuadrante2tf.setBackground(java.awt.Color.white);
        Cuadrante2tf.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Cuadrante2tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cuadrante2tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cuadrante2tfActionPerformed(evt);
            }
        });

        Correctorlbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Correctorlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Correctorlbl.setText("asdasdas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cuadrante4tf)
                            .addComponent(Cuadrante1tf, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cuadrante2tf, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(Cuadrante3tf)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(Correctorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cuadrante1tf, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(Cuadrante2tf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cuadrante4tf, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(Cuadrante3tf))
                .addGap(18, 18, 18)
                .addComponent(Correctorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cuadrante2tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cuadrante2tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cuadrante2tfActionPerformed

    private void Cuadrante1tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cuadrante1tfKeyPressed

    }//GEN-LAST:event_Cuadrante1tfKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_N) {
            // validar si es par
            if (Cuadrante2tf.getText() == "") {
                Correctorlbl.setText("Incorrecto");
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_M) {
            // validar si es impar
            if (Cuadrante1tf.getText() == "") {
                Correctorlbl.setText("Incorrecto");
            }
        } else if (evt.getKeyCode() == evt.VK_Z) {
            if (Cuadrante4tf.getText() == "") {
                Correctorlbl.setText("Incorrecto");
            }
            
        } else if (evt.getExtendedKeyCode() == evt.VK_X) {
            if (Cuadrante3tf.getText() == "") {
                Correctorlbl.setText("Incorrecto");
            }
            
        }
    }//GEN-LAST:event_formKeyPressed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Correctorlbl;
    private javax.swing.JTextField Cuadrante1tf;
    private javax.swing.JTextField Cuadrante2tf;
    private javax.swing.JTextField Cuadrante3tf;
    private javax.swing.JTextField Cuadrante4tf;
    // End of variables declaration//GEN-END:variables
}
